### ISSUE TITLE
Create Screencast on how to add liquidity to pancakeswap

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/amm_nnn_nvm#2]
This should be for novice users and explain in detail how to add liquidity to pancakeswap with metamask

German example:
https://youtu.be/JPelHUkkvSg?t=464

**Comment by 0x471** [comment]
Uploaded to youtube, sent the link from telegram. Waiting for your comments :)

**Comment by 0x471** [comment]
https://www.youtube.com/watch?v=kXSisOPk5l4
